# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0003_create_model_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='body_text',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='entry',
            name='headline',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
